const config = require(`${process.cwd()}/structures/botconfig/config.json`);
const {
  Client,
  Message,
  MessageEmbed
} = require('discord.js');
const moment = require("moment");
const voucher_codes = require("voucher-code-generator");
const schema = require(`${process.cwd()}/structures/models/premium-code`);

module.exports = {
  name: "premium-gencode",
  aliases: [],
  usage: '',
  description: "",
  category: "ownerOnly",
  cooldown: 0,
  userPermissions: "",
  botPermissions: "",
  ownerOnly: false,
  toggleOff: false,

  /**
   * @param {Client} client 
   * @param {Message} message
   * @param {String[]} args
   */

  async execute(client, message, args, ee, prefix) {
    try {

      if (!message.member.roles.cache.has(client.premiumActivator)) return message.reply({
        embeds: [new MessageEmbed()
          .setTitle(`${client.allEmojis.x} Premium System`)
          .setDescription(`You don't have permission to use these commands!`)
          .setColor(ee.wrongcolor)
        ]
      })

      let codes = [];

      let plan = args[0];

      const plans = ["monthly", "yearly"];

      if (!plan) return message.reply({
        embeds: [new MessageEmbed()
          .setTitle(`${client.allEmojis.x} Premium System`)
          .setDescription(`Please provide a valid plan!
Avalable Plans: \`monthly\` \`yearly\``)
          .setColor(ee.wrongcolor)
        ]
      });

      if (!plans.includes(plan.toLowerCase())) return message.reply({
        embeds: [new MessageEmbed()
          .setTitle(`${client.allEmojis.x} Premium System`)
          .setDescription(`Please provide a valid plan!
Avalable Plans: \`monthly\` \`yearly\``)
          .setColor(ee.wrongcolor)
        ]
      });

      let time;
      // if (plan === "daily") time = Date.now() + 86400000;
      // if (plan === "weekly") time = Date.now() + 86400000 * 7;
      if (plan === 'monthly') time = Date.now() + 86400000 * 30;
      if (plan === 'yearly') time = Date.now() + 86400000 * 365;

      let amount = args[1]
      if (!amount) return message.reply({
        embeds: [new MessageEmbed()
          .setTitle(`${client.allEmojis.x} Premium System`)
          .setDescription(`Please provide a number how much codes you want to generate!`)
          .setColor(ee.wrongcolor)
        ]
      });

      for (var i = 0; i < amount; i++) {
        const codePremium = voucher_codes.generate({
          pattern: '####-####-####'
        })

        const code = codePremium.toString().toUpperCase()

        const find = await schema.findOne({
          code: code
        })

        if (!find) {
          schema.create({
            code: code,
            plan: plan,
            expiresAt: time
          })

          codes.push(`${i + 1}- ${code}`)
        }
      }

      message.reply({
        embeds: [new MessageEmbed()
          .setTitle(`${client.allEmojis.y} Premium System`)
          .setDescription(`Generated **${codes.length} Codes**
**Code:** ||\`${codes.join("\n")}\`||
**Plans Type:** ${plan}
**Expires:** ${moment(time).format("dddd, MMMM Do YYYY")}`)
          .setColor(ee.color)
        ]
      });

      const premiumLog = client.channels.cache.get(config.botlogs.premiumLogChannel)
      if (!premiumLog) return;

      return premiumLog.send({
        embeds: [new MessageEmbed()
          .setColor(ee.color)
          .setTitle(`__New Premium Redeem Code Generated:__`)
          .setDescription(`**Generated:** ${codes.length} Codes
**Redeem Code:** ||\`${codes.join("\n")}\`||
**Plan Type:**  ${plan}
**Generated By:** ${message.author.tag} (||${message.author.id}||)
**Expires At:** ${moment(time).format("dddd, MMMM Do YYYY")}`)
          .setThumbnail(`${message.guild.iconURL({dynamic: true})}`)
          .setFooter({
            text: `Generated ${codes.length} new Premium Redeem Code!`
          })
          .setTimestamp()
        ]
      })


    } catch (e) {
      console.log(e)
    }
  },
};